**import the Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ML-Dataset.csv to ML-Dataset.csv

In [ ]:
import pandas as pd
Drone_data = pd.read_csv('ML-Dataset.csv')
Drone_data
Drone_data.head(5)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0

In [ ]:
Drone_data.tail(5)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,60,Lithium Battery,250,2244.0,8999.0,75.0
817,Radhikadro e449 Drone,Professional Drone,100,Lithium Battery,350,2447.0,4999.0,51.0
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,102,Lithium Battery,400,1799.0,6999.0,74.0
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,60,Lithium Battery,250,2799.0,5999.0,53.0
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,100,Lithium Battery,300,2705.0,8999.0,69.0

In [ ]:
Drone_data.shape

(821, 8)

In [ ]:
print("Number of all Drone =", Drone_data.shape[0])

Number of all Drone = 821

In [ ]:
print("Number of all columns = ", Drone_data.shape[1])

Number of all columns =  8

In [ ]:
Drone_data.dtypes

Name              object
Type              object
Control Range      int64
Battery Type      object
Weight             int64
Price            float64
Actual Price     float64
Discount (%)     float64
dtype: object

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
Drone_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821 entries, 0 to 820
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           821 non-null    object
 1   Type           821 non-null    object
 2   Control Range  821 non-null    int64
 3   Battery Type   821 non-null    object
 4   Weight         821 non-null    int64
 5   Price          813 non-null    float64
 6   Actual Price   813 non-null    float64
 7   Discount (%)   810 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 51.4+ KB

In [ ]:
Drone_2 =  Drone_data[['Name','Type','Control Range','Battery Type','Weight', 'Price','Actual Price']]
Drone_2.head(4)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0

In [ ]:
Drone_2.to_csv('Modified-Drone-Dataset.csv')

**Delete column from data**

In [ ]:
Drone_3 = Drone_data.drop(columns=['Battery Type', 'Actual Price'], axis = 1)
Drone_3

,Name,Type,Control Range,Weight,Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,200,2297.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,500,10255.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,150,1994.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,150,2455.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,200,4998.0,16.0
...,...,...,...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,60,250,2244.0,75.0
817,Radhikadro e449 Drone,Professional Drone,100,350,2447.0,51.0
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,102,400,1799.0,74.0
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,60,250,2799.0,53.0
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,100,300,2705.0,69.0

In [ ]:
Drone_2 = Drone_data[['Type','Control Range','Weight','Price']]
Drone_2.head(6)

                 Type  Control Range  Weight    Price
0          Mini Drone             40     200   2297.0
1          Mini Drone            300     500  10255.0
2  Professional Drone            102     150   1994.0
3          Mini Drone             50     150   2455.0
4          Mini Drone            200     200   4998.0
5          Mini Drone            100     200   4376.0

In [ ]:
Drone_2.head(4)

                 Type  Control Range  Weight    Price
0          Mini Drone             40     200   2297.0
1          Mini Drone            300     500  10255.0
2  Professional Drone            102     150   1994.0
3          Mini Drone             50     150   2455.0

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
Dro_dict = {'Name': "Drone_Name",
            'Type': "Drone_Type",
            'Control Range': "Range",
            'Battery Type': "Type_of_Battery",
            'Weight': "Drone_Weight",
            'Price': "Drone_Price",
            'Actual Price': "Real_Price",
            'Discount  (%)': "Discount"}

In [ ]:
Drone_data = Drone_data.rename(columns = Dro_dict)
Drone_data.head(3)

,Drone_Name,Drone_Type,Range,Type_of_Battery,Drone_Weight,Drone_Price,Real_Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0

In [ ]:
Drone_data.select_dtypes(include = 'object').head(3)

,Drone_Name,Drone_Type,Type_of_Battery
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery

In [ ]:
Drone_data.select_dtypes(exclude = 'object').head(3)

   Range  Drone_Weight  Drone_Price  Real_Price  Discount (%)
0     40           200       2297.0      4999.0          54.0
1    300           500      10255.0     11000.0           6.0
2    102           150       1994.0      5999.0          66.0

In [ ]:
categorical_col = Drone_data.select_dtypes(include = 'object').columns
categorical_col

Index(['Drone_Name', 'Drone_Type', 'Type_of_Battery'], dtype='object')

In [ ]:
categorical_col = Drone_data.select_dtypes(exclude = 'object').columns
categorical_col

Index(['Range', 'Drone_Weight', 'Drone_Price', 'Real_Price', 'Discount (%)'], dtype='object')

In [ ]:
Drone_df = Categorical_col =Drone_data.select_dtypes(include = 'object')
Drone_df

,Drone_Name,Drone_Type,Type_of_Battery
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,Lithium Battery
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,Lithium Battery
...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,Lithium Battery
817,Radhikadro e449 Drone,Professional Drone,Lithium Battery
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,Lithium Battery
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,Lithium Battery
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,Lithium Battery

In [ ]:
num_df = Categorical_col = Drone_data.select_dtypes(exclude = 'object')
num_df

     Range  Drone_Weight  Drone_Price  Real_Price  Discount (%)
0       40           200       2297.0      4999.0          54.0
1      300           500      10255.0     11000.0           6.0
2      102           150       1994.0      5999.0          66.0
3       50           150       2455.0      4999.0          50.0
4      200           200       4998.0      5999.0          16.0
..     ...           ...          ...         ...           ...
816     60           250       2244.0      8999.0          75.0
817    100           350       2447.0      4999.0          51.0
818    102           400       1799.0      6999.0          74.0
819     60           250       2799.0      5999.0          53.0
820    100           300       2705.0      8999.0          69.0

[821 rows x 5 columns]

In [ ]:
Categorical_col_List = list(Drone_data.select_dtypes(include = 'object').columns)
Categorical_col_List

['Drone_Name', 'Drone_Type', 'Type_of_Battery']

In [ ]:
Numerical_col_List = list(Drone_data.select_dtypes(exclude = 'object').columns)
Numerical_col_List

['Range', 'Drone_Weight', 'Drone_Price', 'Real_Price', 'Discount (%)']

In [ ]:
Drone_data.duplicated().any()

np.True_

In [ ]:
Drone_data.duplicated().any()

np.True_

In [ ]:
Drone_data.head(20)

,Drone_Name,Drone_Type,Range,Type_of_Battery,Drone_Weight,Drone_Price,Real_Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0
5,ERH India A17 Aerial Drone with 4K Dual Camera...,Mini Drone,100,Lithium Battery,200,4376.0,5999.0,27.0
6,Kidsbuddy New Good Quality Quadcopter E88 WIFI...,Mini Drone,15,AA Rechargeable Battery,350,2299.0,12999.0,82.0
7,tmwilla Foldable-RC-Quadcopter-Altitude-Hold-H...,Professional Drone,117,AA Battery,300,1884.0,4999.0,62.0
8,CLYSOL New Good Quality Quadcopter E88 WIFI Dr...,Mini Drone,100,Lithium Battery,400,2326.0,12999.0,82.0
9,Clubics RC Brushless Motor J18 Drone 4k hd Cam...,Professional Drone,100,Lithium Battery,400,12600.0,13999.0,9.0
10,tmwilla Drone WiFi Camera Drone Remote Control...,Professional Drone,50,Lithium Battery,400,2658.0,11999.0,77.0
11,nexell j2 black 00223 Drone,Professional Drone,100,Lithium Battery,500,5115.0,8000.0,36.0
12,"JOYBOX Foldable Drone with Full HD Camera, WiF...",Mini Drone,100,AA Rechargeable Battery,433,2099.0,2899.0,27.0
13,TodFod E88 Pro Drone 4k HD foldable With Camer...,Professional Drone,50,Lithium Battery,360,2059.0,4999.0,58.0
14,Playtastic A888 PRO Drone with 90° ESC Camera ...,Professional Drone,5,Lithium Battery,1140,5490.0,6990.0,21.0
15,Ezerio E88 Pro Drone 4k HD Foldable Camera Min...,Mini Drone,10,AA Alkaline Battery,400,2273.0,4999.0,54.0
16,Ezerio J2 Drones Long Distance Hd Camera With ...,Mini Drone,50,AA Battery,250,2791.0,12999.0,78.0
17,markif E98 PRO PLUS Drone,Mini Drone,120,Lithium Battery,820,2371.0,3999.0,40.0
18,tmwilla Drone With HD Dual Camera Brushless Mo...,Professional Drone,102,Lithium Battery,400,1799.0,6999.0,74.0
19,tmwilla Drone Rolling Gesture Control Wi-Fi Ca...,Professional Drone,102,Lithium Battery,400,1799.0,6999.0,74.0

In [ ]:
Drone_data[Drone_data.duplicated()]

,Drone_Name,Drone_Type,Range,Type_of_Battery,Drone_Weight,Drone_Price,Real_Price,Discount (%)
478,Swa Mi E88 Pro Foldable Remote Control Drone D...,Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0
609,Swa Mi Mini dron with Camera Hd Dual Camera Wi...,Professional Drone,100,Lithium Battery,100,2244.0,8999.0,75.0
630,"Swa Mi High Quality E88 Pro Drone HD, Dual Cam...",Professional Drone,100,Lithium Battery,100,2705.0,8999.0,69.0

In [ ]:
Drone_d2 = Drone_data.drop_duplicates()

In [ ]:
Drone_d2.shape

(818, 8)

In [ ]:
df = Drone_d2.isnull().sum().reset_index()
df.columns = ['column','null_records']
df['% null_records'] = (df['null_records']/818)*100
df

            column  null_records  % null_records
0       Drone_Name             0        0.000000
1       Drone_Type             0        0.000000
2            Range             0        0.000000
3  Type_of_Battery             0        0.000000
4     Drone_Weight             0        0.000000
5      Drone_Price             8        0.977995
6       Real_Price             8        0.977995
7     Discount (%)            11        1.344743

In [ ]:
Drone_d2['Type']

0              Mini Drone
1              Mini Drone
2      Professional Drone
3              Mini Drone
4              Mini Drone
              ...
816    Professional Drone
817    Professional Drone
818    Professional Drone
819    Professional Drone
820    Professional Drone
Name: Type, Length: 818, dtype: object

In [ ]:
Drone_d2['Type'].value_counts()

Type
Professional Drone    427
Mini Drone            391
Name: count, dtype: int64