In [25]:
#Install Pandas 
#  Or
!pip install pandas

Requirement already satisfied: pandas in c:\users\komal\appdata\local\programs\python\python314\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\komal\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\komal\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\komal\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\komal\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Import pandas 
import pandas as pd

# chaeck vesrsion 
print("Pandas Version:", pd.__version__)

Pandas Version: 3.0.2

In [5]:
data = [10,20,30,40,50]              # it is list = 1D 
print(data)

[10, 20, 30, 40, 50]

In [6]:
data = [10,20,30,40,50]          # still 1D 
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
# A series is a one-daimensinal array with labels (index)
data = [10,20,30,40,50]                                                # Series is 1D array like list 
series = pd.Series(data, index=['A','B','C','D','E'])

print("Series Example:")
print(series)

Series Example:
A    10
B    20
C    30
D    40
E    50
dtype: int64

In [8]:
# Creating a Data Frame using a dictinary

data_dict = {
    'Name': ['Alice','Bob','Charlie','David','Eva'],
    'Age': [25,30,35,40,45],
    'Salary': [5000,43000,300,2000,4009]

}

df = pd.DataFrame(data_dict)                  # 2D array like table row and columns (table = row+columns
print("DataFrame Exmaples:")
print(df)

DataFrame Exmaples:
      Name  Age  Salary
0    Alice   25    5000
1      Bob   30   43000
2  Charlie   35     300
3    David   40    2000
4      Eva   45    4009

In [9]:
# Display top bottom rows
print(df.head(3))            # First 3 rows,(show on the top data)

      Name  Age  Salary
0    Alice   25    5000
1      Bob   30   43000
2  Charlie   35     300

In [10]:
print(df.tail(2))                      #used to see last row of data  (last data)

    Name  Age  Salary
3  David   40    2000
4    Eva   45    4009

In [11]:
# basic info 
print(df.info())               #used to get basic info about datafeame

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes
None

In [12]:
# summary Statistics            
print(df.describe())         #it is gives summary of numeric data ,count, mean,std,min,max

             Age        Salary
count   5.000000      5.000000
mean   35.000000  10861.800000
std     7.905694  18057.329432
min    25.000000    300.000000
25%    30.000000   2000.000000
50%    35.000000   4009.000000
75%    40.000000   5000.000000
max    45.000000  43000.000000

In [13]:
# Column names 
print(df.columns)           # see column names show kart

Index(['Name', 'Age', 'Salary'], dtype='str')

In [14]:
# Shape of dataset (rows, column)
print(df.shape)           # tell sixe of dataframe how many rows and columns

(5, 3)

In [15]:
# Selecting one column 
print(df['Name'])                 #name dakhvto /series titile deto

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str

In [16]:
# Selecting multiple column 
print(df[['Name', 'Salary']])

      Name  Salary
0    Alice    5000
1      Bob   43000
2  Charlie     300
3    David    2000
4      Eva    4009

In [17]:
# Selecting by index position 
print(df.iloc[0])                # First row / select data by position

Name      Alice
Age          25
Salary     5000
Name: 0, dtype: object

In [18]:
print(df.iloc[1:3])            # Row 1 to 2

      Name  Age  Salary
1      Bob   30   43000
2  Charlie   35     300

In [19]:
print(df.iloc[1:2])

  Name  Age  Salary
1  Bob   30   43000

In [20]:
# Selecting by Label                      
print(df.loc[0:2, ['Name','Salary']])         # Rows 0-2 , spesefic columns

      Name  Salary
0    Alice    5000
1      Bob   43000
2  Charlie     300

In [21]:
df             # all table

      Name  Age  Salary
0    Alice   25    5000
1      Bob   30   43000
2  Charlie   35     300
3    David   40    2000
4      Eva   45    4009

In [22]:
df['Tax'] = df['Salary'] *0.10
print(df)

      Name  Age  Salary     Tax
0    Alice   25    5000   500.0
1      Bob   30   43000  4300.0
2  Charlie   35     300    30.0
3    David   40    2000   200.0
4      Eva   45    4009   400.9

In [23]:
# Add n new column 
df['Tax'] = df['Salary'] *0.10

In [24]:
# Update existing column 
df['Salary'] = df['Salary'] + 5000

In [25]:
# Delete a column 
df.drop('Tax', axis=1, inplace= True)

In [26]:
# Arithmetic operations 
df['Bonus'] = df['Salary'] * 0.05
print(df)

      Name  Age  Salary    Bonus
0    Alice   25   10000   500.00
1      Bob   30   48000  2400.00
2  Charlie   35    5300   265.00
3    David   40    7000   350.00
4      Eva   45    9009   450.45

In [27]:
# Intruduction missing values 
df.loc[2, 'Age'] = None

print("With Missing Data:\n", df)

# Check for all values 
print(df.isnull())

# Fill missing values
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Drop rows missing data
# df.dropna (inplace = True)
# print("After handling missing Data:\n", df)

With Missing Data:
       Name   Age  Salary    Bonus
0    Alice  25.0   10000   500.00
1      Bob  30.0   48000  2400.00
2  Charlie   NaN    5300   265.00
3    David  40.0    7000   350.00
4      Eva  45.0    9009   450.45
    Name    Age  Salary  Bonus
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3  False  False   False  False
4  False  False   False  False

C:\Users\komal\AppData\Local\Temp\ipykernel_12680\3705597217.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

0    25.0
1    30.0
2    35.0
3    40.0
4    45.0
Name: Age, dtype: float64

In [28]:
# Filter Data where Age >30 
print(df[df['Age'] >30])

# Multiple conditions 
print(df[(df['Age'] >30) & (df['Salary']> 600000)])

    Name   Age  Salary   Bonus
3  David  40.0    7000  350.00
4    Eva  45.0    9009  450.45
Empty DataFrame
Columns: [Name, Age, Salary, Bonus]
Index: []

In [29]:
# Sort by salary 
print(df.sort_values(by='Salary',ascending=False))

# Sort by Multiple columns 
print(df.sort_values(by=['Age', 'Salary'], ascending=[True,False]))

#Rnk the salaries 
df['Salary_Rank']= df['Salary'].rank(ascending= False)
print(df)

      Name   Age  Salary    Bonus
1      Bob  30.0   48000  2400.00
0    Alice  25.0   10000   500.00
4      Eva  45.0    9009   450.45
3    David  40.0    7000   350.00
2  Charlie   NaN    5300   265.00
      Name   Age  Salary    Bonus
0    Alice  25.0   10000   500.00
1      Bob  30.0   48000  2400.00
3    David  40.0    7000   350.00
4      Eva  45.0    9009   450.45
2  Charlie   NaN    5300   265.00
      Name   Age  Salary    Bonus  Salary_Rank
0    Alice  25.0   10000   500.00          2.0
1      Bob  30.0   48000  2400.00          1.0
2  Charlie   NaN    5300   265.00          5.0
3    David  40.0    7000   350.00          4.0
4      Eva  45.0    9009   450.45          3.0

In [30]:
# Group by example
group_data = df.groupby('Age')['Salary'].mean()
print(group_data)

Age
25.0    10000.0
30.0    48000.0
40.0     7000.0
45.0     9009.0
Name: Salary, dtype: float64

In [31]:
# Multiple aggrgations 
agg_data = df.groupby('Age').agg({'Salary': ['mean', 'max', 'min']})
print(agg_data)

       Salary
         mean    max    min
Age
25.0  10000.0  10000  10000
30.0  48000.0  48000  48000
40.0   7000.0   7000   7000
45.0   9009.0   9009   9009

In [32]:
# merging & joining Dataframe

In [33]:
dept_data = pd.DataFrame({
    'Name' : ['Alice', 'Bob','Charli','David', 'Eva'],
    'Department':['HR', 'IT', 'finance', 'It', 'HR']
})

merged_df = pf = pd.merge(df,dept_data, on='Name')
print(merged_df)

    Name   Age  Salary    Bonus  Salary_Rank Department
0  Alice  25.0   10000   500.00          2.0         HR
1    Bob  30.0   48000  2400.00          1.0         IT
2  David  40.0    7000   350.00          4.0         It
3    Eva  45.0    9009   450.45          3.0         HR

In [34]:
# Concatenation

In [35]:
df1 = df.head(2)
df2 = df.tail(2)

combined = pd.concat([df1, df2])
print(combined)

    Name   Age  Salary    Bonus  Salary_Rank
0  Alice  25.0   10000   500.00          2.0
1    Bob  30.0   48000  2400.00          1.0
3  David  40.0    7000   350.00          4.0
4    Eva  45.0    9009   450.45          3.0

In [36]:
# Statistical & Mathmatical Functions

In [37]:
print("Mean Salary:", df['Salary'].mean())
print("Max Age:", df['Age'].max())
print("Min Age:", df['Age'].min())
print("Standard Deviation of Salary:", df['Salary'].std())

Mean Salary: 15861.8
Max Age: 45.0
Min Age: 25.0
Standard Deviation of Salary: 18057.32943156324

In [38]:
# ADd a Data column

In [39]:
df['Joining_Date'] = pd.date_range(start ='2020-01-01', periods=len(df), freq='YE')

# Extract year
df['Joining_Year'] = df['Joining_Date'].dt.year

print(df[['Name', 'Joining_Date', 'Joining_Year']])
df

      Name Joining_Date  Joining_Year
0    Alice   2020-12-31          2020
1      Bob   2021-12-31          2021
2  Charlie   2022-12-31          2022
3    David   2023-12-31          2023
4      Eva   2024-12-31          2024

      Name   Age  Salary    Bonus  Salary_Rank Joining_Date  Joining_Year
0    Alice  25.0   10000   500.00          2.0   2020-12-31          2020
1      Bob  30.0   48000  2400.00          1.0   2021-12-31          2021
2  Charlie   NaN    5300   265.00          5.0   2022-12-31          2022
3    David  40.0    7000   350.00          4.0   2023-12-31          2023
4      Eva  45.0    9009   450.45          3.0   2024-12-31          2024

In [40]:
# Export final Data

In [41]:
# save Final Data
df.to_csv('Pandas-final_output.csv',index=False)
print("Data Saved Successfully!")

Data Saved Successfully!

In [42]:
# Pandas Assignment

In [43]:
#1. Create a Pandas Series using a list of 5 random numbers and custom index names.
#     Then print the series and its data type.
Data = [10,20,30,40,50]
index = ["A", "B", "C","D", "E"]
series = pd.Series(data, index=index)
print("Series Example:")
print(series)

Series Example:
A    10
B    20
C    30
D    40
E    50
dtype: int64

In [43]:
# 2. Create a DataFrame with columns: "Student_Name", "Maths", "Science", "English".
#     Fill it with 5 sample student records and display the top 3 rows using head().
df = pd.DataFrame({
    "Student_Name": ["Komal","Riya","Sara","Kiya","Siya"],
    "Maths":[80,33,44,55,66],
    "Science":[22,44,55,66,33],
    "English":[45,65,78,34,89]
})
print(df.head(3))

  Student_Name  Maths  Science  English
0        Komal     80       22       45
1         Riya     33       44       65
2         Sara     44       55       78

In [44]:
# 3. Import a CSV file (use any sample dataset) into a DataFrame.
#     Display the number of rows and columns using shape, and print column names.
df = pd.DataFrame({
    "Student_Name": ["Komal","Riya","Sara","Kiya","Siya"],
    "Maths":[80,33,44,55,66],
    "Science":[22,44,55,66,33],
    "English":[45,65,78,34,89]
})
print(df.columns)
print(df.shape)

Index(['Student_Name', 'Maths', 'Science', 'English'], dtype='str')
(5, 4)

In [45]:
# 4. Add a new column named "Total_Marks" that sums all three subject scores.
# Then create another column "Average" by dividing Total_Marks by 3.
df["Total_Marks"] =( df["Maths"]+ df["Science"]+ df["English"] )
df["Average"] = df["Total_Marks"] /3
print(df)

  Student_Name  Maths  Science  English  Total_Marks    Average
0        Komal     80       22       45          147  49.000000
1         Riya     33       44       65          142  47.333333
2         Sara     44       55       78          177  59.000000
3         Kiya     55       66       34          155  51.666667
4         Siya     66       33       89          188  62.666667

In [46]:
# 5. Introduce a missing value (NaN) in the "Science" column and then:
#     (a) Identify missing values using isnull()
#     (b) Replace the missing value with the column mean using fillna().
df.loc[2, "science"] = None
print(df.isnull())
df["science"].fillna(df["Science"].mean(),inplace=True)
print(df)

   Student_Name  Maths  Science  English  Total_Marks  Average  science
0         False  False    False    False        False    False     True
1         False  False    False    False        False    False     True
2         False  False    False    False        False    False     True
3         False  False    False    False        False    False     True
4         False  False    False    False        False    False     True
  Student_Name  Maths  Science  English  Total_Marks    Average science
0        Komal     80       22       45          147  49.000000     NaN
1         Riya     33       44       65          142  47.333333     NaN
2         Sara     44       55       78          177  59.000000    None
3         Kiya     55       66       34          155  51.666667     NaN
4         Siya     66       33       89          188  62.666667     NaN

C:\Users\komal\AppData\Local\Temp\ipykernel_828\1925479676.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["science"].fillna(df["Science"].mean(),inplace=True)

In [47]:
# 6. Filter and display all students whose "Average" score is greater than 75.
top_students = df[df["Average"] > 75]
print(top_students)

Empty DataFrame
Columns: [Student_Name, Maths, Science, English, Total_Marks, Average, science]
Index: []

In [48]:
# 7. Sort the DataFrame by "Total_Marks" in descending order and show the top 3 performers.
sorted_df = df.sort_values(by="Total_Marks",ascending=False)
print(sorted_df.head(3))

  Student_Name  Maths  Science  English  Total_Marks    Average science
4         Siya     66       33       89          188  62.666667     NaN
2         Sara     44       55       78          177  59.000000    None
3         Kiya     55       66       34          155  51.666667     NaN

In [51]:
# 8 Group students based on thier "English" score range(like above or below 70)
# and find the mean of"maths" and "Science" marks foe each group
df['English_group'] = df['English'].apply(lambda x: 'Above 70' if x>= 70 else 
'Below 70')
result = df.groupby('English_group') [['Maths', 'Science']].mean()
print(result)

               Maths  Science
English_group
Above 70        55.0     44.0
Below 70        56.0     44.0

In [70]:
# 9. Merge two DataFrames:
#     (a) One with "Student_Name" and "Total_Marks"
#     (b) Another with "Student_Name" and "Sports_Score"
#     Then create a new column "Overall_Score" = Total_Marks + Sports_Score.

df1 = (df[["Student_Name", "Total_Marks"]])
df2 = pd.DataFrame({
    "Student_Name": ["Komal","Nish","Sunita","Kiran","nikhul"],
    "Sports_Score":[20,33,55,33,22]
})
merged = pd.merge(df1,df2, on="Student_Name")

merged["Overall_Score"] =merged["Total_Marks"]+merged["Sports_Score"] 
print(merged)

  Student_Name  Total_Marks  Sports_Score  Overall_Score
0        Komal          147            20            167

In [1]:
# 10 Export the final DataFrame to a CSV file on your Desktop (use os library to define path)
# and verify is the file is sucessfully created using os.path.exist
import os
import pandas as pd
data = {
    "Name": ["Amit", "Riya", "John"],
    "Age": [21, 22, 23],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
file_path = os.path.join(desktop_path, "final_dataframe.csv")

df.to_csv(file_path, index=False)

if os.path.exists(file_path):
    print("File successfully created at:", file_path)
else:
    print("File creation failed.")

File successfully created at: C:\Users\komal\Desktop\final_dataframe.csv